import type { Metadata } from 'next';
import type { Session } from 'next-auth';
import { Noto_Sans_JP } from 'next/font/google';
import { Providers } from './providers';

const notoSansJapanese = Noto_Sans_JP({
  weight: '400',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { session: Session } }) {
  return (
    <html lang="en">
      <Providers session={params.session}>
        <body className={notoSansJapanese.className}>{children}</body>
      </Providers>
    </html>
  );
}
