services:
  api:
    container_name: "api"
    build: ./backend
    restart: always
    tty: true
    ports:
      - 8000:8000
    env_file: ./backend/.env
    volumes:
      - ./backend:/app/backend
    networks:
      - local-net

  frontend:
    container_name: "frontend"
    build: ./frontend
    restart: always
    tty: true
    ports:
      - 3000:3000
    networks:
      - local-net
    volumes:
      - ./frontend:/app/frontend

networks:
  local-net:
    driver: bridge
